version: '3.3'
services:
  # Service discovery cluster setup
  consul1:
    image: cap1573/consul
    container_name: node1
    command: agent -server -bootstrap-expect=3 -node=node1 -bind=0.0.0.0 -client=0.0.0.0 -datacenter=dc1
  consul2:
    image: cap1573/consul
    container_name: node2
    command: agent -server -retry-join=node1 -bootstrap-expect=3 -node=node2 -bind=0.0.0.0 -client=0.0.0.0 -datacenter=dc1
    depends_on:
      - consul1
  consul3:
    image: cap1573/consul
    container_name: node3
    command: agent -server -retry-join=node1 -bootstrap-expect=3 -node=node3 -bind=0.0.0.0 -client=0.0.0.0 -datacenter=dc1
    depends_on:
      - consul1
  # Add external node with UI dashboard
  consul4:
    image: cap1573/consul
    container_name: node4
    command: agent -retry-join=node1 -node=node4 -bind=0.0.0.0 -client=0.0.0.0 -datacenter=dc1 -ui
    ports:
      - 8500:8500
    depends_on:
      - consul2
      - consul3
   # Add database
  paas-mysql:
    image: cap1573/mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      container_name: paas-mysql
    ports:
      - "3306:3306"
    # Important data persistence
    volumes:
      - ./mysql:/var/lib/mysql
   # Add tracing
  jaeger:
    image: cap1573/jaeger
    ports:
      - "6831:6831/udp"
      - "16686:16686"
  # Add circuit breaker dashboard (commented out)
#  hystrix-dashboard:
#    # Image name
#    image: cap1573/hystrix-dashboard
#    ports:
#      - "9002:9002"
  # Add monitoring
  prometheus:
    image: cap1573/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
  # Monitoring dashboard, default credentials: admin/admin
  grafana:
    image: cap1573/grafana
    ports:
      - "3000:3000"
